apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dnssd-service-instances.proclaim.dogmatiq.io
  labels:
    app.kubernetes.io/name: proclaim.dogmatiq.io
    app.kubernetes.io/part-of: proclaim
spec:
  scope: Namespaced
  group: proclaim.dogmatiq.io
  names:
    plural: dnssd-service-instances
    singular: dnssd-service-instance
    kind: DNSSDServiceInstance
    categories:
      - dnssd
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - instance
              properties:
                instance:
                  type: object
                  required:
                    - name
                    - serviceType
                    - domain
                    - targetHost
                    - targetPort
                  properties:
                    name:
                      type: string
                      x-kubernetes-validations:
                        - message: instance name is immutable
                          rule: self == oldSelf
                    serviceType:
                      type: string
                      x-kubernetes-validations:
                        - message: service type is immutable
                          rule: self == oldSelf
                    domain:
                      type: string
                      x-kubernetes-validations:
                        - message: domain is immutable
                          rule: self == oldSelf
                    targetHost:
                      type: string
                    targetPort:
                      type: integer
                      format: uint16
                    priority:
                      type: integer
                      format: uint16
                    weight:
                      type: integer
                      format: uint16
                    ttl:
                      type: integer
                      format: uint16
                      default: 60
                    attributes:
                      # Note that attributes is an ARRAY of objects, not a SINGLE
                      # OBJECT as you might expect.
                      #
                      # This is because DNS-SD allows for multiple sets of
                      # attributes, each having its own TXT record.
                      #
                      # Instances should almost always have exactly one TXT record,
                      # and therefore one item in this array. The meaning of
                      # multiple TXT records is protocol specific, it MUST NOT be
                      # assumed that clients will merge the attributes from
                      # different sets.
                      #
                      # See https://www.rfc-editor.org/rfc/rfc6763#section-6.8
                      #
                      # ----------------------------------------------------------
                      #
                      # The objects within the array are key/value pairs of
                      # attributes.
                      #
                      # A key with an empty string value in the YAML is treated as
                      # a boolean attribute in the TXT record.
                      #
                      # See https://www.rfc-editor.org/rfc/rfc6763#section-6.4
                      #
                      # This means it is impossible to represent an associative
                      # attribute with an empty string value in the TXT record.
                      #
                      # ----------------------------------------------------------
                      #
                      # This approach is a compromise taken due to a limition
                      # within Kubernetes CRDs schema; it is not possible to
                      # STRICTLY define an object with additional properties that
                      # are either strings or booleans.
                      #
                      # We believe this compromise will still allow for the most
                      # common use cases, while keeping the schema as simple as
                      # possible.
                      #
                      # See https://kubernetes.io/blog/2019/06/20/crd-structural-schema/
                      type: array
                      items:
                        type: object
                        additionalProperties:
                          type: string

            status:
              type: object
              properties:
                conditions:
                  description: List of conditions to indicate the status of the DNS-SD service instance.
                  type: array
                  items:
                    type: object
                    required:
                      - status
                      - type
                    properties:
                      type:
                        description: Type of the condition.
                        type: string
                      status:
                        description: Status of the condition.
                        type: string
                        enum:
                          - "Unknown"
                          - "True"
                          - "False"
                      reason:
                        description: A machine-readable explanation for the condition's last transition.
                        type: string
                      message:
                        description: A human-readable description that complements the reason.
                        type: string
                      observedGeneration:
                        description: The generation of the DNS-SD resource that was known to the controller when this condition was set.
                        type: integer
                        format: int64
                      lastTransitionTime:
                        description: The time at which this condition was last changed.
                        type: string
                        format: date-time
                  x-kubernetes-list-map-keys:
                    - type
                  x-kubernetes-list-type: map

                providerID:
                  type: string
                advertiserID:
                  type: string
                advertiseGeneration:
                  type: integer
                providerDescription:
                  type: string
                  default: Unknown
                status:
                  type: string
                  default: Pending
                advertisedAt:
                  type: string
                  format: datetime

      additionalPrinterColumns:
        - name: Instance Name
          description: The name of the DNS-SD instance to advertise
          type: string
          jsonPath: .spec.instance.name

        - name: Service Type
          description: The type of service that the instance provides
          type: string
          jsonPath: .spec.instance.serviceType

        - name: Domain
          description: The domain name under which the DNS records are created
          type: string
          jsonPath: .spec.instance.domain

        - name: Host
          description: The host name at which the service can be reached
          type: string
          jsonPath: .spec.instance.targetHost

        - name: Port
          description: The port number at which the service can be reached
          type: integer
          jsonPath: .spec.instance.targetPort

        - name: Provider
          description: The provider used to publish the DNS records
          type: string
          jsonPath: .status.providerDescription

        - name: Ready
          description: Indicates whether the DNS records are in sync with the desired state.
          type: string
          jsonPath: .status.conditions[?(@.type=="Ready")].status

        - name: Reason
          description: The reason for the current readiness status.
          type: string
          jsonPath: .status.conditions[?(@.type=="Ready")].reason

        - name: Advertised
          type: date
          jsonPath: .status.advertisedAt

        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
