apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-viewer" (include "proclaim.fullname" .) }}
  labels:
    {{- include "proclaim.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "proclaim.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "proclaim.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
