apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dnssd-service-instances.proclaim.dogmatiq.io
  labels:
    app.kubernetes.io/name: proclaim.dogmatiq.io
    app.kubernetes.io/part-of: proclaim
spec:
  scope: Namespaced
  group: proclaim.dogmatiq.io
  names:
    plural: dnssd-service-instances
    singular: dnssd-service-instance
    kind: DNSSDServiceInstance
    shortNames:
      - dnssd
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - name
                - service
                - domain
                - targetHost
                - targetPort
              properties:
                name:
                  type: string
                service:
                  type: string
                domain:
                  type: string
                targetHost:
                  type: string
                targetPort:
                  type: integer
                  format: uint16
                priority:
                  type: integer
                  format: uint16
                weight:
                  type: integer
                  format: uint16
                ttl:
                  type: integer
                  format: uint16
                attributes:
                  type: array
                  items:
                    type: object
                    additionalProperties:
                      type: string
