apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dnssd-service-instances.proclaim.dogmatiq.io
  labels:
    app.kubernetes.io/name: proclaim.dogmatiq.io
    app.kubernetes.io/part-of: proclaim
spec:
  scope: Namespaced
  group: proclaim.dogmatiq.io
  names:
    plural: dnssd-service-instances
    singular: dnssd-service-instance
    kind: DNSSDServiceInstance
    categories:
      - dnssd
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Instance Name
          description: The name of the instance to advertise
          type: string
          jsonPath: .spec.name
        - name: Service Type
          description: The type of service that the instance provides
          type: string
          jsonPath: .spec.service
        - name: Domain
          description: The domain name under which the DNS-SD records are created
          type: string
          jsonPath: .spec.domain
        - name: Target Host
          description: The host name at which the service can be contacted
          type: string
          jsonPath: .spec.targetHost
        - name: Target Port
          description: The port number at which the service can be contacted
          type: integer
          jsonPath: .spec.targetPort
        - name: Status
          description: The current status of the DNS-SD service instance object
          type: string
          jsonPath: .status.status
        - name: Provider
          description: The provider used to publish the DNS records
          type: string
          jsonPath: .status.providerDescription
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - name
                - service
                - domain
                - targetHost
                - targetPort
              properties:
                name:
                  type: string
                service:
                  type: string
                domain:
                  type: string
                targetHost:
                  type: string
                targetPort:
                  type: integer
                  format: uint16
                priority:
                  type: integer
                  format: uint16
                weight:
                  type: integer
                  format: uint16
                ttl:
                  type: integer
                  format: uint16
                  default: 60
                attributes:
                  type: array
                  items:
                    type: object
                    additionalProperties:
                      type: string
            status:
              type: object
              properties:
                providerId:
                  type: string
                providerDescription:
                  type: string
                advertiserId:
                  type: string
                status:
                  type: string
                  default: "Pending"
