apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: instances.dns-sd.proclaim.dogmatiq.io
  labels:
    app.kubernetes.io/name: proclaim.dogmatiq.io
    app.kubernetes.io/part-of: proclaim
spec:
  scope: Namespaced
  group: dns-sd.proclaim.dogmatiq.io
  names:
    plural: instances
    singular: instance
    kind: Instance
    shortNames:
      - inst
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - name
                - service
                - domain
                - host
                - port
              properties:
                name:
                  type: string
                  description:
                service:
                  type: string
                domain:
                  type: string
                host:
                  type: string
                port:
                  type: integer
                  format: uint16
                priority:
                  type: integer
                  format: uint16
                weight:
                  type: integer
                  format: uint16
                attributes:
                  type: object
                  additionalProperties:
                    type: string
