apiVersion: v1
kind: ServiceAccount
metadata:
  name: proclaim
  labels:
    app.kubernetes.io/name: proclaim.dogmatiq.io
    app.kubernetes.io/part-of: proclaim
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: proclaim
  labels:
    app.kubernetes.io/name: proclaim.dogmatiq.io
    app.kubernetes.io/part-of: proclaim
rules:
  - apiGroups:
      - proclaim.dogmatiq.io
    resources:
      - dnssd-service-instances
    verbs:
      - get
      - list
      - watch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: proclaim-viewer
  labels:
    app.kubernetes.io/name: proclaim.dogmatiq.io
    app.kubernetes.io/part-of: proclaim
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: proclaim
subjects:
  - kind: ServiceAccount
    name: proclaim
    namespace: proclaim # TODO
